# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe54f4b86eba735d31fd8d78a25333f348ecb9b92a1187a01f730eb43851b209304916ef9078ddb84c54833d40fda4f347b9d9101782e5c8bef2cf0c22799682

test:
  secret_key_base: 2442be427ee0ef7e1aeb1add13ac14e1b641d704906898456cb6a691042a813c66e5ad8effe2e4280885d76b01ed98c4e98bd0e73eaed9a1e5492f64f3a91f8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
